package project_euler;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

public class euler_2 {
    public static void main(String[] args) {
        int limit = 4000000;
        long sum = 0;

        int n = 1;
        while (true) {
            int fib = fib(3 * n); //Only each third number in the Fibonacci sequence is even-valued
            if (fib > limit)
                break;
            sum += fib;
            n++;
        }

        System.out.println(sum);
    }

    private static Integer fib(Integer n) {
        if (n <= 1)
            return n;
        return fib(n - 2) + fib(n - 1);
    }
}
